version: '3'

volumes:
  data_dev:
  redis_dev:
  shared_data:

networks:
  sentinela_network:
    driver: bridge

services:
  db:
    image: postgres:13.1-alpine
    container_name: sentinela_db
    restart: always
    volumes:
      - data_dev:/var/lib/postgresql/data
      - shared_data:/var/shared
    env_file: .env
    ports:
      - "5440:5432"
    networks:
      - sentinela_network
  redis:
    image: 'redis:7.0.10-alpine'
    restart: always
    #command: redis-server --requirepass root
    volumes:
      - 'redis_dev:/data'
    ports:
      - "6381:6379"
    networks:
      - sentinela_network