
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sentinela_development

test:
  <<: *default
  database: sentinela_test

production:
  <<: *default
  database: sentinela_production
  username: sentinela
  password: <%= ENV["SENTINELA_DATABASE_PASSWORD"] %>
