
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DB']%>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  # config docker
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default

test:
  <<: *default
  database: sentinela_test

production:
  <<: *default
  database: sentinela_production
  username: sentinela
  password: <%= ENV["SENTINELA_DATABASE_PASSWORD"] %>
